apiVersion: v1
kind: Service
metadata:
  # keep it under 24 chars
  name: tectonic-lb
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-lb
    component: ingress-controller
  annotations:
    tectonic-operators.coreos.com/upgrade-strategy: Patch
    tectonic-operators.coreos.com/upgrade-behaviour: UpgradeIfExists
spec:
  type: NodePort
  selector:
    k8s-app: tectonic-lb
    component: ingress-controller
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32000
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32001
    - name: health
      protocol: TCP
      port: 10254
      targetPort: 10254
      nodePort: 32002
