apiVersion: v1
data:
  config: W2RlZmF1bHRdCnJlZ2lvbiA9IHVzLXdlc3QtMQo=
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQUpGSEhRT0VCM0xVVTdWNFEKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gYmJVMHZ5VnljZ2lDUkloNHV6SlI5NEhJV1dPNFY0SmlqeDk1dUYxYwo=
kind: Secret
metadata:
  name: cluster-secret
  namespace: kube-system
type: Opaque
